### ISSUE TITLE
live chat

### ISSUE THREAD

**Issue by ChillerDragon** [ChillerDragon/github-meta#5]

**Comment by ChillerDragon** [comment]
hi jopstr

**Comment by Jupeyy** [comment]
hi

**Comment by ChillerDragon** [comment]
yo

**Comment by Jupeyy** [comment]
how are you bro

**Comment by ChillerDragon** [comment]
pogpog

**Comment by ChillerDragon** [comment]
good u?

**Comment by Jupeyy** [comment]
i am fine too

**Comment by ChillerDragon** [comment]
pressing enter doesnt work .-.

**Comment by Jupeyy** [comment]
yeah, but at least we can share some media here, even videos

**Comment by ChillerDragon** [comment]
true pog

**Comment by ChillerDragon** [comment]
but no .demo files cuz :trollface:

**Comment by Jupeyy** [comment]
i'd say, still better than IRC :^)

**Comment by ChillerDragon** [comment]
wowow no

**Comment by ChillerDragon** [comment]
![image](https://user-images.githubusercontent.com/20344300/235456536-fbd507b3-da43-4b82-9182-4ea431b70e51.png)

**Comment by ChillerDragon** [comment]
MEME

**Comment by ChillerDragon** [comment]
![gif](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2F2.bp.blogspot.com%2F-3OiuF304qC0%2FVZwgfY9PMXI%2FAAAAAAABZ0I%2FAuS3ymJjPyg%2Fs1600%2F07-funny-gif-158-cute-dog.gif&f=1&nofb=1&ipt=a445d8ad8a6b6bedc89213af83369fdc71a01e45814e7f2ed66566a37267257d&ipo=images)

**Comment by ChillerDragon** [comment]
lets make private repo and use it as dms xd

**Comment by ChillerDragon** [comment]
xxxxxxxxxxxxD

**Comment by Jupeyy** [comment]
this is so 2024, i like it. we even have reactions, epic

**Comment by ChillerDragon** [comment]
> this is so 2024, i like it. we even have reactions, epic

ikr future is now

**Comment by ghost** [comment]
@MyNewBie

**Comment by ghost** [comment]
@MyNewBie hello sir, I would like to contact you. You can reach me via discord: nouaa

**Comment by MyNewBie** [comment]
> @MyNewBie hello sir, I would like to contact you. You can reach me via discord: nouaa

Hi, how i can help you ?

**Comment by ChillerDragon** [comment]
@RandomHexagons hi im the dude that opend the :eye: :eye:  issue :D 

I got all your comments via mail but could respond anymore so I do it here. Yes it was a discord bot token but it was invalid you probably already deleted the bot so everything is fine. But good idea to close down the repository. Im glad you are not mad that I poked around in your stuff :sweat_smile:

**Comment by michaelvqq** [comment]
Nah it's cool. Thank you again man.
