### ISSUE TITLE
private dms with teero

### ISSUE THREAD

**Issue by ChillerDragon** [ChillerDragon/github-meta#8]

**Comment by ChillerDragon** [comment]
how would they know

**Comment by ChillerDragon** [comment]
uwu

**Comment by TsFreddie** [comment]
abuse

**Comment by ChillerDragon** [comment]
no u

**Comment by ChillerDragon** [comment]
where teero

**Comment by Teero888** [comment]
hiiiiii uwu

**Comment by Teero888** [comment]
How is this private?

**Comment by ChillerDragon** [comment]
ayo

**Comment by ChillerDragon** [comment]
@Teero888 its private trust me

**Comment by ChillerDragon** [comment]
fred must have hacked us somehow

**Comment by ChillerDragon** [comment]
i mean the idea is the same @Teero888 you just do the same thing in a private repo.I just cba to create one and wait for you to accpet the invite

**Comment by Teero888** [comment]
well I guess it works xD

**Comment by ChillerDragon** [comment]
it does!

**Comment by ChillerDragon** [comment]
you can send images

**Comment by ChillerDragon** [comment]
> well I guess it works xD

you can reply

**Comment by Teero888** [comment]
Not the nicest chat system aber ich mecker nicht

**Comment by ChillerDragon** [comment]
its a perfectly functional chat with groups and private groups

**Comment by ChillerDragon** [comment]
one annoyance is that "enter" to send does not work

**Comment by Teero888** [comment]
I'm on my phone on my way home

**Comment by ChillerDragon** [comment]
ah do you even get live refreshes?

**Comment by ChillerDragon** [comment]
app or browser?

**Comment by Teero888** [comment]
Can you send images and stuff?

**Comment by Teero888** [comment]
![Whataboutsomewickedskills_9bbae3_12149196.png](https://github.com/user-attachments/assets/5613790c-a353-4bd7-8be1-6f3a1801cd21)

**Comment by ChillerDragon** [comment]
yes

**Comment by Teero888** [comment]
It works yay

**Comment by ChillerDragon** [comment]
![image](https://github.com/user-attachments/assets/7e45c23d-5d3c-425d-af34-ce0bf5530642)

**Comment by ChillerDragon** [comment]
![image](https://github.com/user-attachments/assets/7e9ae454-b815-4216-bcc6-a0c7076c4134)

**Comment by ChillerDragon** [comment]
rip gif

**Comment by ChillerDragon** [comment]
![image](https://github.com/user-attachments/assets/2d2a5213-6b6e-418e-b0f7-4ecc0b726691)

**Comment by ChillerDragon** [comment]
![second hand](https://cloud.githubusercontent.com/assets/5912527/10680719/3137c9f0-78f0-11e5-86be-199d7f39270c.gif)

**Comment by SollyBunny** [comment]
i am hacker and have hacked this dm, please give me 5000 robux or i will send this chat to kimchi johny yes papa

**Comment by TsFreddie** [comment]
why do these always turn into meme dumps
